name: Unit Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        project: [tests/PuppeteerSharpToolkit.Tests]
    uses: dusrdev/actions/.github/workflows/reusable-dotnet-test-mtp.yaml@main
    with:
      platform: ${{ matrix.platform }}
      dotnet-version: 9.0.x
      test-project-path: ${{ matrix.project }}